### ISSUE TITLE
Requesting a `databases firewalls remove --rule` flag

### ISSUE THREAD

**Issue by tlhunter** [digitalocean/doctl#1017]
**What is the problem this feature would solve? Please describe.**
For an application I'm building I would like to have a GitHub action temporarily connect to a database to perform some migrations. The machine that the action runs on is going to be one of many different machines with an IP address that's hard to know ahead of time. I would like to add the ip address rule tag temporarily, execute the migration, then remove it.

Adding the rule is straightforward and can be done with the following github action YAML:

```yaml
  - name: Determine Public IP
    id: ip
    uses: haythem/public-ip@v1.2

  - name: Allow GitHub CI Runner
    run: doctl databases firewalls append ${{ secrets.DO_FW_ID }} --rule ip_addr:${{ steps.ip.outputs.ipv4 }}
```

The output of this command looks something like this:

```
UUID      ClusterUUID  Type     Value
UUID_1    DB_ID_1    ip_addr    1.2.3.4
UUID_1    DB_ID_1    ip_addr    AA.BB.CC.DD
UUID_1    DB_ID_2    ip_addr    10.XX.XX.XX/XX
```

**Describe the solution you'd like**
Unfortunately, scripting a solution to then remove the rule is quite a bit more complex. One needs to grep the output from the previous command searching for an occurrence of the IP that was provided as input, sed/awk out the first column, assign that value somehow to another variable, and use it later for the removal command.

What would be convenient is if the `remove` subcommand was symmetrical to the `append` subcommand. For example, the following would be straightforward to implement (and also be more intuitive--it's the first thing I reached for):

```yaml
  - name: Disallow GitHub CI Runner
    run: doctl databases firewalls remove ${{ secrets.DO_FW_ID }} --rule ip_addr:${{ steps.ip.outputs.ipv4 }}
```

**Additional context**
I believe the functionality was added in #950. In that PR the author even hinted that the `remove` command would follow the `doctl databases firewalls remove --rule type:value` pattern.

I do see that it's possible to have duplicate tags (like `ip_addr:1.2.3.4` repeated twice), which is perhaps the reason why a UUID is used for removal instead of the tag. That said, I believe adding the `remove --rule` flag and have it remove all repeated rules would be the desired behavior. This is kind of like comparing the linux `kill PID` command (analogous to the `--uuid` flag) with the `killall COMMAND` command (analogous to the proposed `--rule` flag), where different scenarios requires one or the other.

**Comment by scotchneat** [comment]
Thanks for bringing this to our attention @tlhunter. We'll have to look into adding the functionality you describe. We're also open to reviewing PRs if you have time to contribute.

Meanwhile, I'd like to offer a workaround so you can get your workflow in place until we can get the functionality properly implemented. Since doctl commands can format output as json (`doctl dbs fw ls <db-uuid> -o json`), that output can be piped to other tools like jq, which is already available to github workflows. 

I just tried this command and was able to delete a rule by IP address value without knowing the rule uuid first:

`doctl dbs fw remove $DB_UUID --uuid $(doctl dbs fw ls $DB_UUID -o json | jq -cr '.[] | select ( .value == "$FW_RULE_IP_VALUE") | .uuid')`

You'll just need to make sure the workflow populates the appropriate environment variables or customize this command to fit your needs.

**Comment by tlhunter** [comment]
Thanks, @scotchneat, the `-o json` flag worked like a charm.

While GitHub does offer the ability to [extract output variables from shell scripts](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter), I actually didn't need it since the list and remove can be performed in the same step.

Feel free to close this ticket if you'd like, though I suspect it would still be a beneficial feature. I probably won't have the spare time to tackle a PR for a few months.

**Comment by scotchneat** [comment]
That's great to hear @tlhunter. Please don't hesitate to reopen this request for further discussion.
