### ISSUE TITLE
[Feature Request] Deploy zip to Functions

### ISSUE THREAD

**Issue by H4ad** [digitalocean/doctl#1221]
**What is the problem this feature would solve? Please describe.**

Using this folder structure:

- project.yml
- packages
  - sample
    - example
      - index.js
      - package.json
      - node_modules

To deploy to DigitalOcean Functions, I need to run `doctl serverless deploy .`.
Then it will run `npm install --production` and then it will zip the content and deploy to Functions.

**Describe the solution you'd like**

I have a library to zip the contents of `node_modules` and minify the files called [node_modules_packer](https://github.com/H4ad/node-modules-packer) and I want to use this library to create a zip file and then upload it to Functions.

Serverless Framework has a solution called [artifact](https://www.serverless.com/framework/docs/providers/aws/guide/packaging#artifact), which looks like:

```yml
package:
  artifact: path/to/my-artifact.zip
```

So the solution I wanted was something like:

```yml
packages:
  - name: sample
    functions:
      - name: hello
        file: 'path/to/my-artifact.zip'
        zipped: true
        main: ''
        runtime: 'nodejs:18'
        web: true
```

**Additional context**

I spent a couple hours reading the source code of this CLI my discovers was: `doctl` call [@nimbella/nimbella-cli](https://www.npmjs.com/package/@nimbella/nimbella-cli), and then call [@nimbella/nimbella-deployer](https://www.npmjs.com/package/@nimbella/nimbella-deployer).

The `@nimbella/nimbella-deployer` has support to deploy the content of the Function as zip file [here](https://github.com/nimbella/nimbella-deployer/blob/4841ca48f49ea1ce9244906294a6e35298469c75/src/deploy-struct.ts#L62) and [here](https://github.com/nimbella/nimbella-deployer/blob/4841ca48f49ea1ce9244906294a6e35298469c75/src/deploy-struct.ts#L57).

In theory, it already has support for deploying zip files but `docl` doesn't enable this functionality.

**Comment by joshuaauerbachwatson** [comment]
I believe the stated goal can already be achieved without changes to `doctl` or the `nimbella` libraries.    The only restriction is that either
1. the build to run `node_modules_packer` must run in the `packages/sample/example` directory, or 
2. it must run somewhere off the `lib` directory (where `lib` is a peer of `packages`) or 
3. it must run external to the project structure before `doctl sls deploy` is. called but deposit the resulting zip file either in `packages/sample/example` directory or somewhere under `lib`.

The structure for (1) is
- project.yml
- packages
  - sample
    - example
      - build.sh
      - (any other files you need for your build)
      - .include

where the file `.include` contains a single text line with the path to your zip file, which must not be absolute or. contain `..` directives (ie, the file must end up somewhere under `example`).

The structure for (2) is
- project.yml
- lib
      - build.sh
      - (any other files you need for your build)
- packages
  - sample
    - example
      - .include

where the file `.include` contains a single text line with `../../../lib/further-path-to-your-zip-file`.   In this case, the zip file must live somewhere under `lib`.

The structure for (3) is
- project.yml
- packages
  - sample
    - example
      - .include

and `.include` has the correct access path for the where your zip file ends up after the build (either form (1) or form (2) shown above).   You can omit `.include` entirely if and only if your zip file ends up being the only file in the the `example` directory (but I would encourage you to use `.include` anyway for clarity).

Note that `doctl` will recognize either `lib/build.sh` or `packages/sample/example/build.sh` as special and will run it (it should be marked executable).   It will run it in lieu of `npm install` even if there is a `package.json` because a user-supplied build script takes precedence.

**Comment by H4ad** [comment]
Thanks for your answer @joshuaauerbachwatson!

I tested your options and here what I discover:

- `.include` file cannot contain relative path like `../../../lib/further-path-to-your-zip-file`, so I moved the zip folder inside `packages/sample/example` and leave the content of `.include` as `my-zip-file.zip`.
- `package.yml` should be modified to be able to find the entry point, in my zip file I had: `dist/index.js` exporting `main`, so my configuration inside `package.yml` becomes: `main: 'dist/index.main'`.

And that's it, everything works great!

For anyone who reach here and wants an example of what we talk, [see here](https://github.com/H4ad/serverless-adapter-examples/tree/master/examples/nestjs-digital-ocean) and example project with NestJS.
