### ISSUE TITLE
--interactive false still gives a confirmation prompt

### ISSUE THREAD

**Issue by benmordaunt** [digitalocean/doctl#1267]
Using `--interactive false` with `doctl compute droplet delete` still produces the

```
Warning: Are you sure you want to delete 2 Droplets? (y/N) ?
```

prompt. How can a response be expected to a prompt in a non-interactive environment? `doctl` should handle this as an implicit `--force`.

**Comment by andrewsomething** [comment]
Hi @benmordaunt,

Thanks for flagging this. The `--interactive` flag is a recent addition, and it looks like we did not incorporate it with the pre-existing confirmation dialogs.

I think we'll want to require `--force` explicitly. That was the behavior before adding the `--interactive` flag and keeps true to the intention of the prompt to prevent accidental deletion while still working in CI/scripting. We can print a warning to stderr pointing to the need to use `--force`.

This would be fixed by: https://github.com/digitalocean/doctl/pull/1265
