### ISSUE TITLE
Deploying functions tries to npm install in wrong directory

### ISSUE THREAD

**Issue by daniellionel01** [digitalocean/doctl#1300]
**Describe the Issue:**
When I deploy my functions directory, it tries to run the `npm install --production ...` command in the wrong directory, as you can see here:
```
$ dotenv -e .env --  doctl serverless deploy functions
Deploying 'PWD/functions'
  to namespace '...'
  on host '...'
Started running npm install --production in PWD/functions/dx/send-email
Started running npm install --production in PWDfunctions/xing/get-candidates
Output of failed build in PWD/functions/packages/dx/send-email
/bin/bash: npm: command not found

Output of failed build in PWD/functions/packages/xing/get-candidates
/bin/bash: npm: command not found


Failures:
Error: While deploying action 'dx/send-email': 'npm install' exited with code 127
While deploying action 'xing/get-candidates': 'npm install' exited with code 127
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I replaced my git directory with PWD for privacy sake.

My packages are located at 'functions/packages/dx/send-email' and 'functions/packages/xing/get-candidates', but it tries to run npm install in 'functions/dx/send-email', which is missing the packages/ directory.

**Environment:**
 - doctl version: 1.84.1-release
 - OS: Pop!_OS 22.04 LTS x86_64
 - Installation method: Snap package

**Additional Details:**
I have successfully deployed my dx/send-email function in the past (a couple of weeks ago) so it seems to me like a new version has broken something.

**Comment by daniellionel01** [comment]
Here's my project.yml
```
environment:
  ...
packages:
  - name: dx
    functions:
      - name: send-email
        binary: false
        runtime: 'nodejs:14'
        web: true
  - name: xing
    functions:
      - name: get-candidates
        binary: false
        runtime: 'nodejs:14'
        web: true
```

**Comment by joshuaauerbachwatson** [comment]
@daniellionel01 thank you for this well documented report.

I believe there are actually two problems here.

1.  The message that is displayed when running a build is misleading.  It indeed omits part of the path.   I don't know how long that bug has been there but possibly a while .. it is easy not to notice as long as things are going well.   In fact, the build is not actually happening in the wrong directory (notice that when the failure is reported it is reported as happening in the expected directory). 
2.  When there are function builds and `doctl` is running under `snap`, you can get failures to find various tools that are, in fact, in your path.   I was able to reproduce this error in a linux image using a `snap` install.   As your transcript shows, `npm` was not found and so the build exited with a 127 code.   I believe this problem relates to the confined execution model that `snap` imposes.  I don't know a lot about `snap` and will need to get help with this part of the problem but obviously we should do something about it.

I will immediately open an internal ticket to fix problem (1).  It is not serious, in a sense, but will result in wasted effort attempting to debug the wrong problem.

To work around problem (2) while we're investigating exactly what to do about it you can
- use remote build:  `doctl sls deploy <dir> --remote-build`.   This will run the build in the runtime container.  I was able to circumvent the problem that way.
- install `doctl` by downloading the latest release from GitHub rather than by using `snap`.  I don't know if that's an option for you.

**Comment by joshuaauerbachwatson** [comment]
The problem of omitting the `/packages` segment from paths, when reporting build progress, is not in `doctl` proper but in another codebase incorporated via a plugin mechanism.   I have fixed that bug, but, because we are in the process of switching over the repository hosting for the other codebase, the fix will queue behind some other changes and may not appear in a `doctl` release immediately.   Note that the spurious message is _not_ related to the actual cause of the build failure.   I'm looking into that separately.

**Comment by daniellionel01** [comment]
I was able to get it working with the "--remote-build" flag. Thanks for the quick response!
