### ISSUE TITLE
--wait does not wait for cloud-init to finish

### ISSUE THREAD

**Issue by ktalebian** [digitalocean/doctl#1334]
**Describe the Issue:**

I'm running the following command:

```
doctl compute droplet create \
  --region "${JX_DO_REGION}" \
  --image "${JX_DO_DROPLET_IMAGE}" \
  --size "${JX_DO_DROPLET_SIZE}" \
  --ssh-keys "${JX_DO_SSH_KEY}" \
  --enable-monitoring \
  --enable-ipv6 \
  --vpc-uuid "${vpcId}" \
  --user-data-file "${DIR}/user-data.sh" \
  --wait \
  --verbose \
  --enable-private-networking \
  "${JX_DO_HOST_NAME}"
```

With my `user-data.sh` file being

```
#!/bin/sh
echo "==> Starting bootstrapping"
touch /root/file.txt

echo "=== Updating Apt and install Snapd ==="
apt update
apt install snapd

echo "=== Installing Dependencies ==="
snap install gh docker
apt install maven -y

echo "==> Completed bootstrapping"
```

Even though I have the `--wait,` the script "finishes," when I SSH onto the box and `tail -f /var/log/cloud-init-output.log` - I can still see the cloud-init being executed. 

I was expecting the command `doctl compute droplet create` would wait until everything is bootstrapped (or errored) before returning. 

If my understanding is incorrect, how can I confirm that the init script has finished before I continue with the next steps?

**Environment:**
 - doctl version: 1.18.0
 - OS Command running from: macOS
 - OS of the Droplet: Ubuntu

**Comment by ChiefMateStarbuck** [comment]
Hello @ktalebian, 
Thank you for the question. The `--wait` command only waits for the droplet itself to boot (`Wait for Droplet creation to complete before returning`). As for your `user-data-file`, let me do some discovery on how we can `--wait` on this. I'll get back to you shortly.

**Comment by ktalebian** [comment]
@ChiefMateStarbuck thank you! 

At the moment, I am using effectively doing a `doctl compute ssh "$host" --ssh-command "tail -f /var/log/cloud-init-output.log" > "$logFile" &` and then tailing the log file and checking for `Cloud-init v. 22.2-0ubuntu1~18.04.3 finished` line before continuing.

**Comment by andrewsomething** [comment]
Currently there is no way for doctl to know if a cloud-init script is in-progress. The `--wait` flag relies on the API reporting the Droplet as active. Knowing the status of cloud-init would require accessing the Droplet itself or an agent or other mechanism running on the Droplet.

You're current method is very close to what I generally recommend as a work around. One small improvement might be to use cloud-init's own status command rather than tailing the log. E.g. this would block until cloud-init completes:

    cloud-init status --wait

There is a bit of previous discussion here: https://github.com/digitalocean/doctl/issues/773

**Comment by ChiefMateStarbuck** [comment]
closed due to stale state.
