### ISSUE TITLE
Add filtering to volume lists

### ISSUE THREAD

**Issue by collinpeters** [digitalocean/doctl#137]
I can use `doctl compute droplet list` to get a list of all droplets and I can use `doctl compute droplet list dropletname` to get just a single droplet.

Likewise I can do `doctl compute volume list` to get a list of all volumes, but I cannot get a single volume. `doctl compute volume list volumename` still returns all volumes.

**Comment by bryanl** [comment]
Hello,

Let's see if I'm understanding what you reporting. `doctl compute volume list` doesn't work like `doctl compute droplet list`. There's a subtle difference between them. The droplet version takes a filter and the volume does not. This is not a huge amount of work. I'll throw this in the queue. 

Thanks for reporting!

**Comment by claudioandre** [comment]
Isn't just a new 'ListByTag()' in volumes.go needed?  If so, I would like to improve my go skills. 

Bryan, is there any possibility you mentor me?

**Comment by xMudrii** [comment]
Here are my personal opinion on this. Keep in mind I didn't spend a lot of time analyzing it so it could be very wrong.

I would just change `RunVolumeList()` to look for number of arguments in `os.Args`.
If it is `0` - list all images, `> 0` - get volume by ID (or return array of volumes if more than 1).

`ListByTag()` looks only like API function returning droplet data by tag, it's not processing input, input is processed by `RunDropletList()`. Anyways in volumes it could be done only by ID (looking at API docs, I didn't saw searching for volume by name), volumes doesn't have it's tag.

Maybe this is worst possible way, but I would love to hear idea of some DO collaborator :D
Also maybe it would not be bad to have some contribution mini-tutorial, what is what instead of mentoring so it helps everyone, but maybe it would just give very low results for much effort :P

**Comment by bryanl** [comment]
Like droplets, there volumes have an id, and a name. List could be augmented, so that it works like you prescribe.
