### ISSUE TITLE
doctl registry garbage-collection start --force moves the registry to RO mode but don't run garbage collector

### ISSUE THREAD

**Issue by paivin-dn** [digitalocean/doctl#1464]
**Describe the Issue:**
Hello! I tried to run the garbage-collection via the doctl but got that my container registry moved to RO mode and I sew the following action status:
```shell
doctl registry garbage-collection get-active 
UUID                                    Registry Name    Status                         Created At                       Updated At                       Blobs Deleted    Bytes Freed
df2dec4a-7718-468e-a0de-a858e7a0df27    <asd>            waiting for delete requests    2023-11-27 19:18:33 +0000 UTC    2023-11-27 19:20:34 +0000 UTC    0                0

**Comment by trpouh** [comment]
currently experiencing the same issue, the garbage collection process has been stuck for 4 hours in status "waiting for delete requests"

**Comment by andrewsomething** [comment]
@trpouh - `doctl` only makes an API call to initiate garbage collection. It does not have any role in the actual garbage collection process. Please open a support ticket so that the appropriate team can investigate your issue with more context about your registry and account:  https://cloudsupport.digitalocean.com/s/
