### ISSUE TITLE
Serverless: Can not install Serverless in Linux x64

### ISSUE THREAD

**Issue by vdlr** [digitalocean/doctl#1545]
`doclt serverless install` return error when running on Linux Intel x64:

_Downloading...Error: serverless support is not available for 32-bit linux_

**Environment:**
 - doctl version: doctl-1.108.0-linux-386
 - OS: ubuntu 22.04.4 running on an Intel-Core-i7
 - Installation method: tar downloaded

**Additional Details:**

Error is due to the way to determine 32 or 64 bit host machine, at file _go/serverless.go_ 

Probably that is not the way to avoid command run in 32bit Intel Linux system:
https://github.com/digitalocean/doctl/blob/ebbaa708f9aed2f1aed968863d0563c24be77d6d/do/serverless.go#L434-L438

Maybe this could help: https://github.com/shirou/gopsutil/pull/745

**Comment by andrewsomething** [comment]
Hi @vdlr,

Thanks for opening this issue. It looks like we are using the architecture that doctl was complied for rather than the host system, and you are running the 32-bit version of doctl (`doctl-1.108.0-linux-386`). Could you explain a bit more about your platform? I'd live to better understand the use case.

**Comment by loosla** [comment]
@andrewsomething Is the AMD build, `doctl-1.108.0-linux-amd64.tar.gz`, suitable for a 64-bit Intel processor in this case? Thanks.

**Comment by vdlr** [comment]
Yes, right! It works, thank you!
