### ISSUE TITLE
bug: fail to create a kube cluster

### ISSUE THREAD

**Issue by drev74** [digitalocean/doctl#1619]
**Describe the Issue:**
I've been using a `doctl` script to create a cluster for months. Today it failed to work with the error below

Error: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 (request "fe2ff026-6ef3-43f7-afd3-9f75464815f9") validation error: autoscale desired max nodes exceed limits, 24 additional nodes but not enough available droplet limit

**Environment:**

 - doctl version:  1.119.1-release
 - OS:  Ubuntu 24.04
 - Installation method:  binary

**Additional Details:**

doctl kubernetes cluster create $1 \
--region $region \
--vpc-uuid $vpcUUID \
--version $kube_version \
--maintenance-window $maintainWindow \
--node-pool "name=$2;size=$size;auto-scale=true;min-nodes=$minNodes;max-nodes=$maxNodes;tag=$owner;tag=$tag;label=ownedBy=$owner;label=managedBy=$managedBy;label=env=$tag"

**Comment by bentranter** [comment]
Hey @drev74,

You're getting that error message because the number of Droplets required to create the Kubernetes cluster exceeds your account's Droplet limit.

You can request a Droplet limit increase by following the instructions [here](https://www.digitalocean.com/community/questions/how-do-i-increase-my-droplet-limit).
