### ISSUE TITLE
Why is there difference between 'tag-name' and 'tag-names' flags?

### ISSUE THREAD

**Issue by xmudrii** [digitalocean/doctl#166]
Just a friendly question - but by was `tag-name` left to error if tag is non-existing? :)
As far as I remember, earlier it would just create Droplet but will not apply tag if it doesn't exist.

Now there is API update and new command in doctl `tag-names` which supports this by default.
Why we have two commands that basically do the same?
Following two commands have same result if `tag1` exists 
```
doctl compute droplet create doctl-2 --image 20822342 --region nyc1 --size 20gb --tag-name tag1
doctl compute droplet create doctl-2 --image 20822342 --region nyc1 --size 20gb --tag-names tag1
```
Yes first is taking string and second can take array but if only one is specified it'll do the same work.

So I think it could be that create new tag is default behavior and make one command from this two. I wanted to know why this isn't done (why we have 2 commands now)? :) I guess I don't see something obvious but I think it's OK. :+1: 

cc @hugocorbucci @daveworth @mchitten

**Comment by mchitten** [comment]
Hey @xmudrii, thanks for asking. As you say, `--tag-name` (singular) is very similar to `--tag-names` (plural) except in a few ways:

1. `--tag-name` only accepts one tag.
2. `--tag-name` tag must already exist.
3. `--tag-names` accepts an array of tags.
4. tags in the `--tag-names` array _do not already have to exist_. If any tags in the array are new, we'll create them and apply them to the Droplet. If any tag names in the array already exist, we'll just apply them to the Droplet.

We didn't just outright do away with `--tag-name` because it would be a pretty sudden change, but we'll be deprecating it at some point soon. I highly recommend using `--tag-names` (plural) for the reasons and benefits described above.

**Comment by xmudrii** [comment]
Thank you for explanation. I understand now why is it done like that and I agree on it. :)
As I understand it now, I'll close this issue.
