### ISSUE TITLE
[Idea] Add list of resources that will be deleted before asking for confirmation

### ISSUE THREAD

**Issue by xmudrii** [digitalocean/doctl#172]
Now, when you execute command like `doctl compute droplet delete 1`, you'll see:
`Warning: Are you sure you want to delete droplet(s) (y/N) ? y`.
But that's all. If you used `--force` flag, you'll neither see confirmation which is OK.

Mine idea, is to show list of Droplets that will be deleted in time of asking for confirmation. If you execute command like above again, you could see something like:
```
Following Droplets will be deleted:
ID		Name			Public IPv4	Private IPv4	Public IPv6	Memory	VCPUs	Disk	Region	Image			Status	Tags
1	droplet	ip					1024	1	30	nyc2	Ubuntu 16.04.1 x64	active	

Warning: This is not reversible process! Are you sure you want to delete droplet(s) (y/N) ?
```

Something like you would see when you execute `apt-get remove` or any other package manager remove/install.

This is just idea, I want feedback from maintainers. I don't think I'll have time to do so, but in some future, it could be done by me if you approve idea. :+1: 

Will not cc lots of maintainers now, let's just call @aybabtme and @andrewsomething =)

**Comment by bnordland** [comment]
Since this was just an idea, I didn't submit a pull request yet, but I did commit code that has the following behavior (https://github.com/bnordland/doctl/commit/d2ca54903966c9a2181817bade2eb94cbdfc3fa5):

```
$ doctl compute droplet delete test test2
Following Droplet(s) will be deleted:
ID		Name	Public IPv4	Private IPv4	Public IPv6	Memory	VCPUs	Disk	Region	Image		Status	Tags
36243836	test	192.241.149.114					512	1	20	nyc1	Debian 8.6 x64	active	
36243845	test2	159.203.191.220					512	1	20	nyc1	Debian 8.6 x64	active	
Warning: Are you sure you want to delete droplet(s) (y/N) ? 
```

Behavior:

1. If force is specified the list is **not** shown
2. If one or more of the droplets specified is not found, an error is shown without showing the list (e.g. Error: droplet with name "test3" could not be found)
2. If doing by ID or Name it'll list the droplets to be deleted is shown before the confirmation as is shown above.

_Note: When doing a delete by tagName it does not show the list (I didn't get to that part as this is more a sample)_

**Comment by xmudrii** [comment]
LGTM. :+1: It's working flawless and as I wanted in idea. Please create pull request so maintainers can take look and merge it. =)

**Comment by bnordland** [comment]
I updated pull request #179 to now properly do delete by tagName showing the list which also required adding support for calling the delete by tagName since the parameter wasn't allowed but the code to handle it was there (oops).
