### ISSUE TITLE
add monitoring to doctl

### ISSUE THREAD

**Issue by mikejennings** [digitalocean/doctl#182]
doesn't appear to be a way to add monitoring when creating a droplet in doctl.

**Comment by xmudrii** [comment]
It's added. It's not available in 1.5.0, but in master branch version there it is.‎There is flag in args.go for monitoring: ‎https://github.com/digitalocean/doctl/blob/master/args.go#L66It's implemented in #170 by @cv                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: MikeSent: utorak, 10. januar 2017. 19.09To: digitalocean/doctlReply To: digitalocean/doctlCc: SubscribedSubject: [digitalocean/doctl] add monitoring to doctl (#182)doesn't appear to be a way to add monitoring when creating a droplet in doctl.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/digitalocean/doctl","title":"digitalocean/doctl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/digitalocean/doctl"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"add monitoring to doctl (#182)"}],"action":{"name":"View Issue","url":"https://github.com/digitalocean/doctl/issues/182"}}}‎
