### ISSUE TITLE
config.yaml file path on Windows

### ISSUE THREAD

**Issue by Linda-chan** [digitalocean/doctl#240]
Looks like doctl use hardcoded path on user profile folder in its code. So on Windows XP it saves config.yaml in «C:\Users\Crow\AppData\Local\doctl\config\» folder (in my case) instead of «C:\Documents and Settings\MSI U100-455RU\Application Data\doctl\config\». doctl should use APPDATA environment variable or SHGetSpecialFolderLocation() function to get correct config folder location.

**Comment by xmudrii** [comment]
I believe this is the problem - https://github.com/digitalocean/doctl/blob/master/commands/xdg_windows.go#L23

It should use `APPDATA` or `LOCALAPPDATA instead of `XDG_CONFIG_HOME` (AFAIK it doesn't exist on Windows).

However, as this sounds like easy change, we could break stuff for some customers (such as XP users). I think we need someone from DO to discuss it internally and propose way to change. One possibility is to ignore that portion of users, while another one (and better) is to check for legacy path if it doesn't exist in new one. This has been already done in past for Linux users so I believe it shouldn't be problem.

/cc @viola @mauricio @lxfontes

**Comment by Linda-chan** [comment]
I didn't get why changing this

````
userName := os.Getenv("USERNAME")
configHome = filepath.Join("C:/", "Users", userName, "AppData", "Local", "doctl", "config")
````

to this

````
configHome := os.Getenv("APPDATA")
configHome = filepath.Join(configHome, "doctl", "config")
````

should break something. Windows XP users my be legacy users but this kind of approach can break everything even on Windows 10 if for some reason APPDATA folder will be in different location.

**Comment by xmudrii** [comment]
True - I just want to collect opinions from DO employees on this one, it's very easy to change.

**Comment by Linda-chan** [comment]
Ok ^^'

**Comment by mauricio** [comment]
@Linda-chan that makes sense, we'd still have to allow for the old place (if there's a config there) but for new installs use the expected place. `SHGetSpecialFolderLocation` might be a better option since it lets the operating system to provide instead of us trying to figure out folder paths.

I don't have a windows box available here, can you test if we get something like this in place?

**Comment by Linda-chan** [comment]
Okay, I will test it. But I don't have Go environment Oo

**Comment by xmudrii** [comment]
If you want I can test it, I've Windows on my box

**Comment by mauricio** [comment]
@Linda-chan @xmudrii did any of you folks make any progress here?

**Comment by xmudrii** [comment]
‎Nothing for now, but I'll take on it over the weekend, if nobody takes it before me. :)

**Comment by xmudrii** [comment]
@mauricio @Linda-chan I've created the PR #295 to address this issue.
