### ISSUE TITLE
Managing Firewalls and Network Resources

### ISSUE THREAD

**Issue by matthewsuan** [digitalocean/doctl#242]
Hi,

Is there anyway to manage firewalls (CRUD) and other Network Resources using Doctl?

Thanks!

**Comment by xmudrii** [comment]
If you think of managing DigitalOcean Cloud Firewalls you can use `doctl compute firewall`. It will show all possible options. You can also type suncommand for more details such as `doctl compute firewall create`.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Matthew SuanSent: sreda, 5. jul 2017. 19.48To: digitalocean/doctlReply To: digitalocean/doctlCc: SubscribedSubject: [digitalocean/doctl] Managing Firewalls and Network Resources (#242)Hi,
Is there anyway to manage firewalls (CRUD) and other Network Resources using Doctl?
Thanks!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/digitalocean/doctl","title":"digitalocean/doctl","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/digitalocean/doctl"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Managing Firewalls and Network Resources (#242)"}],"action":{"name":"View Issue","url":"https://github.com/digitalocean/doctl/issues/242"}}}

**Comment by matthewsuan** [comment]
oh ok my bad. I didnt have the updated version.

Thanks!
