### ISSUE TITLE
How to doctl auth init without input prompt?

### ISSUE THREAD

**Issue by edwinyzh** [digitalocean/doctl#281]
I want to **eliminate** the prompt input of the API token when initializing the authentication. 
I have tried all of the following command formats, but failed - it always prompt me to input the token.

`doctl auth init --access-token ThisIsMyDOApiToken`
`doctl auth init --access-token "ThisIsMyDOApiToken"`
`doctl auth init --access-token=ThisIsMyDOApiToken`

I'm using the latest doctl-1.7.1-windows-4.0-386 release **on widows home 64bit**. Please help.

**Comment by xmudrii** [comment]
@edwinyzh If you type `doctl auth init --access-token "your-do-token"` you will be asked to enter you token, but if you just press enter (without inputting a token), `doctl` will use flag's value to authorize you.

You can also set `DIGITALOCEAN_ACCESS_TOKEN` environmental variable to your DO Token and you will not be explicitly required to authorize with `doctl` in order to use it.

**Comment by edwinyzh** [comment]
Great! I'll use the  DIGITALOCEAN_ACCESS_TOKEN environmental variable. Thanks.

**Comment by Frank-Developer** [comment]
Please for heavens above upgrade your use doctl with multiple envs documentation

**Comment by reinvantveer** [comment]
> @edwinyzh If you type `doctl auth init --access-token "your-do-token"` you will be asked to enter you token, but if you just press enter (without inputting a token), `doctl` will use flag's value to authorize you.
> 
> You can also set `DIGITALOCEAN_ACCESS_TOKEN` environmental variable to your DO Token and you will not be explicitly required to authorize with `doctl` in order to use it.

This appears to no longer work. I set the DIGITALOCEAN_ACCESS_TOKEN env var and it still prompts for input. What's the non-interactive method now?
