### ISSUE TITLE
Incorrect Volume Sizes Created

### ISSUE THREAD

**Issue by jonathantittle** [digitalocean/doctl#285]
**Version**

```
doctl version 1.7.1-release
```

**Command**

```
doctl compute volume create storage01-00 --region nyc3 --size 500GB --desc storage01-00
```

**Result**

```
ID                                      Name             Size       Region    Droplet IDs
d17ac8f7-e78f-11e7-bff6-0242ac117a02    storage01-000    465 GiB    nyc3 
```

Only by passing in 536871MB in place of 500GB am I able to get a 500GB volume as expected. This differs from the way the API works in that 500 is an accepted value and conversion isn't required.

**Test - doctl passing MB in place of GB**

```
doctl compute volume create storage01-00 --region nyc3 --size 536871MB --desc storage01-00
```

**Result**

```
ID                                      Name            Size       Region    Droplet IDs
99bc7cdf-e790-11e7-b41a-0242ac113706    storage01-00    500 GiB    nyc3     
```

**Test - API direct**

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer [token]" -d '{"size_gigabytes":500, "name": "example", "description": "Block store for examples", "region": "nyc3"}' "https://api.digitalocean.com/v2/volumes"
```

**Result**

```
b8f40965-e791-11e7-b41a-0242ac113706    example                500 GiB    nyc3
```

**Comment by xmudrii** [comment]
Hello @jonathantittle! :wave: 
This is intended behavior of `doctl` and API. Actually, the problem is that API is not documented properly.

API (and therefore `doctl`) has field `size_gigabytes`. However, [description](https://developers.digitalocean.com/documentation/v2/#create-a-new-block-storage-volume) states that size is in [gibibytes (GiB)](https://en.wikipedia.org/wiki/Gibibyte).

1 gigabyte (GB) is 1000^3 bytes, while 1 gibibyte (GiB) is 1024^3 bytes.
When you're using API, it's assumed that you're providing size in gibibytes. You can also see it in the response—the result is 500 GiB volume.

With `doctl`, you're allowed to specify do you want 500 GB (465 GiB) or 500 GiB.
The correct `doctl` command is:
```
doctl compute volume create storage01-00 --region nyc3 --size 500GiB --desc storage01-00
```
I hope things are cleaner now. If you have any questions feel free to ping me.

**Comment by honeywild** [comment]
Thanks!
