### ISSUE TITLE
unknown flag: --tag-names

### ISSUE THREAD

**Issue by nathanaherne** [digitalocean/doctl#298]
I get the feeling that this isn't a bug but something I do not completely understand about Tags.

I have created a bash script which creates my droplets. One of the variables in my script are "TAGS", my script checks if the variable is blank or not and if so not blank it adds "--tag-names" and then the "TAGS" the to the doctl command. When the bash script runs the doctl command I get the following error:

unknown flag: --tag-names stuff,things,bob

Weirdly, if I echo the constructed command to terminal then copy/paste it into the terminal and run it manually, it works perfectly.

It is going to be something small, can someone tell me what I am missing please?

**Comment by hugocorbucci** [comment]
I think we're gonna need a bit more information into what doctl command you're running and how you're building that. From the error it looks like it's trying to interpret the flag as being the whole thing (`--tag-names stuff,things,bob`) rather than just `--tag-names`.
Can you share some more into how you're building the doctl droplet create command?

**Comment by nathanaherne** [comment]
The bash command I am using to construct it is `if [ -z "${8}" ]; then DROPLET_TAGS=""; else DROPLET_TAGS="--tag-names ${8}"; fi`

I then pull it into the command as a string using `"$DROPLET_TAGS"`

**Comment by kamaln7** [comment]
Because you are quoting the `"$DROPLET_TAGS"` argument, doctl treats the whole string as one argument. You will need it to be split into two. Make sure that your tag names (`${8}`) do not contain any spaces.

```sh
if [ -z "${8}" ]; then
    DROPLET_TAGS=""
else
    DROPLET_TAGS="--tag-names"
    DROPLET_TAGS+="${8}"
fi
```

Then, `doctl .... $DROPLET_TAGS ...` (without quotes) should work. @nathanaherne, let me know if that helps!

**Comment by kamaln7** [comment]
Closing this issue—feel free to re-open if it is still not working for you.
