### ISSUE TITLE
Exclude access token from config file if defined in environment variable

### ISSUE THREAD

**Issue by aheckler** [digitalocean/doctl#378]
I like to keep my config files in a private GitHub repo so that I can track the changes I make to them. However, `doctl` makes this difficult because the access token is included in `~/.config/doctl/config.yaml`.

I deleted the file and instead use an environment variable to define the access token. This worked, but now I don't have a config file. Running `doctl auth init` again puts the config file back, but with the access token in it.

Maybe it's possible to exclude the access token during `doctl auth init` if it's already defined by an environment variable?

**Comment by kamaln7** [comment]
Sorry for the late response here @aheckler. I have a suggestion, let me know if it works for you.

1. Run `doctl auth init` once in order to get a config file.
2. Edit the file and remove all access tokens from it (search for `access-token` and `auth-contexts`). 

Now, you can run any doctl commands while passing the access token using the `DIGITALOCEAN_ACCESS_TOKEN` env var with the rest of the config coming from the file which you can commit in git. If you run `doctl auth init` or `doctl auth switch` it will re-write the config file _with_ the access token but you shouldn't need to use these commands.

**Comment by aheckler** [comment]
More complicated than I'd like, but it works. :)
