### ISSUE TITLE
Add command "Add ssh key to droplet"

### ISSUE THREAD

**Issue by andpolo96** [digitalocean/doctl#406]
For example:
`doctl compute droplet-action add-ssh-key  <droplet-id> --shh-key <dir-or-ssh-keyvalue>`

**Comment by andpolo96** [comment]
Replace the run of this command manually 
`cat ~/.ssh/id_rsa.pub | ssh username@203.0.113.0 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys" `

**Comment by eddiezane** [comment]
@andpolo96 thanks for the feature request!

I'd recommend you use [`ssh-copy-id`](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2#step-three%E2%80%94copy-the-public-key) here.

I'd prefer not to duplicate `ssh-copy-id`'s functionality since it's baked in with most OpenSSH installations. If you can make a strong case though it's something we'd consider.

**Comment by thagenbeek** [comment]
Well this is not the same behavior, as for ssh-copy-id you would then need a password setup, and that defeats the purpose of passwordless access...
