### ISSUE TITLE
Kubernetes cluster deletion leaves dangling loadbalancer(s)

### ISSUE THREAD

**Issue by waynr** [digitalocean/doctl#437]
## What happens
The following sequence of steps should reproduce the problem:

```
doctl kubernetes cluster create meow
```
Wait for cluster provisioning to finish, then:

```
kubectl --context=do-nyc1-meow apply -f https://raw.githubusercontent.com/digitalocean/digitalocean-cloud-controller-manager/master/docs/controllers/services/examples/http-nginx.yml
```

Wait for the load balancer to appear in the DO control panel (or in the output of `doctl compute load-balancer list`).

```
doctl kubernetes cluster delete meow
```

The cluster should become unavailable almost immediately, but you should continue to see the load balancer in the DO control panel (or in the output of `doctl compute load-balancer list`) until you explicitly do something to delete it.

## What I expect to happen
From my point of view as the user it seems reasonable to expect the loadbalancer to be garbage collected when tearing down the cluster since it was created as a result of an interaction with the cluster.

**Comment by andrewsomething** [comment]
Hi! I've passed this feedback along to our Kubernetes team. Adding support cascading resource deletion is on their roadmap. With the current default approach, deleting the cluster will not automatically delete load balancers or block storage volumes. This is done this way in order to ensure data on PVCs is not lost when deleting a cluster. Similarly, there are use cases that require persisting the IP address which is tied to the LB.

When support for cascading deletion is added to DigitalOcean Kubernetes, well make sure to bring it to doctl as well. I'm going to go ahead and close this issue for now as it won't be actionable until then.

Thanks for the feedback!

**Comment by waynr** [comment]
> use cases that require persisting the IP address which is tied to the LB.

Ah, I hadn't considered this -- thanks for pointing it out!
