### ISSUE TITLE
doctl auth init: Error: unable to read DigitalOcean access token: The handle is invalid.

### ISSUE THREAD

**Issue by tomekceszke** [digitalocean/doctl#573]
There is a problem with initial authentication using following doctl command:
`> doctl auth init`
`DigitalOcean access token: Error: unable to read DigitalOcean access token: The handle is invalid.`

doctl doesn't create config at `\AppData\Local\doctl\config\config.yaml`

Environment:
- Windows 10 1903 x64
- doctl 1.30.0 x64 (tried also with 32bit and older versions)
- cmd, cmd run as admin, power shell
- doctl added to the PATH

**Comment by bentranter** [comment]
I've reproduced this on a fresh Windows 10 VM, going to look into it now.

**Comment by bentranter** [comment]
Ok, the issue here is that we assume `terminal.ReadPassword(0)` works on Windows. While `0` is the file descriptor for stdin on Unix, it's not on Windows. Updating this to be `terminal.ReadPassword(syscall.Stdin)` should fix it on Go 1.12, but it looks like on 1.13 it needs a type conversion from `syscall.Handle` to `int`. Looking into that now, and then I'll open a PR to fix this.
