### ISSUE TITLE
git-style aliases

### ISSUE THREAD

**Issue by aybabtme** [digitalocean/doctl#67]
## What

Allow git-style aliases for commands.
## Why

Some commands are more frequently used than others by users, so allowing people to alias them to their convenience will provide a more ergonomic experience.
## How

Possible impl:
- Add the aliases definitions to the config file.
- Before starting the `cobra` stuff, expand the `os.Args` according to the aliases.

**Comment by bmamlin** [comment]
As an "end user" coming from [tugboat](https://github.com/pearkes/tugboat), the "compute" in `doctl` commands feel extraneous (it doesn't help that my fingers are trained to add an "r" at the end of "compute"). If you could drop the "compute" word from commands it would help.

I was expecting more intuitive commands like:

`$ doctl ssh dropletname`

and

`$ doctl delete dropletname`

and

`$ doctl list droplets`

It was helpful to learn that I could abbreviate "droplet" as "d", but then I was surprised that I couldn't abbreviate "compute" as "c".

It's great to have an up-to-date and actively developed command line tool for DO, so thank you for `doctl`! Making the command line options simpler would be a greatly appreciated enhancement.

----

_Meanwhile, I'll add learning [Go](https://golang.org) to my to-do list, so maybe I can contribute via pull requests instead of just complaining about how much awesomer your great tool could be. :wink:_

**Comment by morbeo** [comment]
I also found the `doctl compute` unnecessarily long so I aliased it to `di` with `alias di='doctl compute '`. I would have aliased it to `do`, but it is a reserved word in bash :(

**Comment by mauricio** [comment]
We're better off letting people configure this in their own shells than trying to add something that's already available.
