### ISSUE TITLE
does doctl support switching between teams?

### ISSUE THREAD

**Issue by vnugent** [digitalocean/doctl#670]
I have an account A that was added to Team T.

I can manage projects and K8s clusters that were created under team T

Now I want to mange K8s clusters in my own account A.  Even though I have added auth context I can't seem to switch them.
```
doctl auth init --context my_own_account
# provide API key
```

**Comment by kamaln7** [comment]
If you run `doctl k8s cluster list --context my_own_account`, do you see the clusters on account A? Passing the `--context` flag to any command lets you specify the auth context to use instead of the default one.

If you saw your own clusters, you can change the default context from account T to account A by running: `doctl auth switch --context my_own_account`.

To switch back, run `doctl auth switch --context team_t_context`. If you didn't create a new context for Team T, chances are its context's name is `default`.
