### ISSUE TITLE
permissions error with doctl snap accessing docker

### ISSUE THREAD

**Issue by JayKayy** [digitalocean/doctl#709]
doctl is unable to access docker to authenticate to the registry when installed via snap.

```
$ doctl registry login
Error: unable to find the Docker CLI binary. Make sure docker is installed
```
But docker is installed via snap

```
$ docker --version
Docker version 18.09.9, build 1752eb3
```

I believe a slot is needed for doctl snap to support :docker-support interface

**Comment by zachgersh** [comment]
@JayKayy - thank you so much for this issue! Hopefully we'll have a fix for you soon.

**Comment by swetank01** [comment]
I am also facing same problem while running "doctl registry login"
@zachgersh  do we have any progress/solution ?

**Comment by swetank01** [comment]
@JayKayy I found a custom solution :  https://stackoverflow.com/questions/60221651/doctl-is-unable-to-find-docker-binary/60237742#60237742 
Hope it will help you..

**Comment by gibiansky** [comment]
@zachgersh 

I just hit this issue and wrote up my experience debugging it:

https://gist.github.com/gibiansky/f4d7167b67eb88422151ff5d4e5fbf9c

The core issue is that snaps can't access `/usr/bin/docker`, so using `exec.LookPath` to check for Docker via an executable is an issue. I had to get rid of `doctl` snap and install it just as an executable. It seems like there's some sort of special Snap docker support (the `docker` interface / connection) but I couldn't figure out if this would help -- I assume it would let you programmatically act like a Docker client, but still wouldn't let you `exec.LookPath` for the docker executable. 

 It seems like until then just installing Releases from Github is maybe preferred to the the snap install? 

Thanks! Hope my little experience write-up helps someone.

**Comment by andrewsomething** [comment]
I wanted to provide a bit of an update here: As @gibiansky explained so well, the confinement provided by the Snap security model prevents `doctl` from calling out to the Docker binary. Additionally, the `docker` Snap interface only gives access to the Docker daemon, which does not provide the login mechanism. In order to address this, we have rewritten the command to not depend on the Docker binary being present (see: https://github.com/digitalocean/doctl/pull/805). This will still require us to get approval from the Canonical Snap team to get write access to the Docker configuration file (`~/.docker/config.json`). We're hopeful that this will be granted.

In the meantime, installing `doctl` directly is a workaround:

https://github.com/digitalocean/doctl#downloading-a-release-from-github

**Comment by braedon** [comment]
Thanks for the update @andrewsomething.

Will #807 work when `~/.docker/config.json` is only accessible to root? Currently even installing `doctl` directly doesn't work unless the permissions on `~/.docker/config.json` are changed.

**Comment by andrewsomething** [comment]
@braedon  Unfortunately, if  `~/.docker/config.json` is owned by `root` and `doctl` is run by a non-root user, it will not be able to access the file without changing its permissions. 

You might consider: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
