### ISSUE TITLE
Feature Request: Upload files/tar to spaces

### ISSUE THREAD

**Issue by Francois-Esquire** [digitalocean/doctl#763]
It would be nice to create build artifacts that we can upload straight to spaces in our CI/CD pipeline (github actions for instance), with the ability to tar directories or upload single files. An optional flag `--mount-path="/path/in/space"` would be great. Is anything currently possible of this sort with `doctl`?

Thank you!

**Comment by bentranter** [comment]
Hey @Francois-Esquire, unfortunately there's no way to do this with `doctl` as of today. `doctl` intentionally doesn't support Spaces, but because the Spaces API is S3 compatible we usually recommend using a compatible CLI tool like `s3cmd` to interact with Spaces.

If you're looking to upload files to Spaces via `s3cmd`, we have documentation at https://www.digitalocean.com/docs/spaces/resources/s3cmd-usage/#upload-files-to-a-space that should help. If you have any questions about its usage or anything else, feel free to ask here.

**Comment by Francois-Esquire** [comment]
Thanks @bentranter ! Yeah, I ended up using an `s3` SDK to help with this. Appreciate your response.
