### ISSUE TITLE
[QUESTION] how to restore volume created with doctl?

### ISSUE THREAD

**Issue by MarcelHaldimann** [digitalocean/doctl#771]
**Describe the Issue:**

Not sure if this is the right place to ask. :) 

I made a script that creates a snapshot of every given volume. This script gets executed with a cronjob in our cluster. For the snapshots I use: 

`doctl compute volume snapshot 92a6f4b0-0000-0000-0000-0a58ac14d018 --snapshot-name test-nginx`

I try to restore the volume with:
https://www.digitalocean.com/docs/kubernetes/how-to/snapshot-volumes/ 

The restore fails because of the "volumesnapshots" is not present in our cluster. Is there a way around it, or do I have to restore the volume in the dashboard and switch it manually in the PersistentVolumeClaim? 

**Environment:**
doctl version 1.38.0-release
Git commit hash: 4cb8a21
release 1.39.0 is available, check it out!

**Additional Details:**
I tried to create the VolumeSnapshot manually in my cluster with the same name and "snapshotContentName" refers to the snapshot name. But this does just create a new snapshot. 

Thanks in advance.

**Comment by timoreimann** [comment]
@MarcelHaldimann :wave: 

The snapshot name you specify in the `PersistentVolumeClaim` refers to the _Kubernetes-local_ snapshot object that is expected to be created through a `VolumeSnapshot` object -- it's not directly related to the snapshot name you specify with `doctl compute volume snapshot`.
Since you're already executing the snapshot from within your cluster, is there anything keeping you from periodically executing `kubectl` with [the YAML described in the same document](https://www.digitalocean.com/docs/kubernetes/how-to/snapshot-volumes/#create-a-snapshot-of-a-volume)? That'd be the canonical, Kubernetes-native way to create snapshots.

You could also restore a `doctl`-created snapshot through the cloud control panel and use [our guide](https://github.com/digitalocean/csi-digitalocean/tree/master/examples/kubernetes/pod-single-existing-volume) to import the resulting volume into your Kubernetes cluster. Personally that option wouldn't be my first choice though since you must be careful to follow the guide precisely -- it's easy to accidentally delete your volume if you miss a step. That warning said, both options should work.

Hope this answers your question, but please let us know if not.

**Comment by MarcelHaldimann** [comment]
Thank you for your response Timo. 

Yes, I saw this part of the documentation. Unfortunately, a little bit too late. Everything is scripted and set up in all of our clusters. And it works great. I don’t have the resources to script it new for an edge case like a restore. 

I think it would be the better way to execute the yaml with kubectl. With the kubernetes nativ way the restore is much easier! 

I tried it yesterday with your guide it worked like a charm. 

Thank you for your clarification.
