### ISSUE TITLE
SSH key public_key not accessible via doctl

### ISSUE THREAD

**Issue by rienafairefr** [digitalocean/doctl#894]
**What is the problem this feature would solve? Please describe.**
When `list`ing or `get`ting a ssh-key, with the `doctl compute ssh-key` subcommand, it's possible to see the fingerprint of the key, but not possible to see the actual public key, which would be useful

**Describe the solution you'd like**
an optional format for the ssh-key field, e.g. `--format PublicKey` that would show the public key string `ssh-rsa ...`. The string is usually very long so showing it should be optional

**Additional context**
The value of that string is already in the API request, at the `public_key` attribute

**Comment by andrewsomething** [comment]
Thanks for this good suggestion. Until it gets implemented, you can work around this by specifying JSON output. E.g.

```
doctl compute ssh-key get <id> -o json
```

This will include the full key.

**Comment by bentranter** [comment]
If anyone would like to take this on for Hacktoberfest, it shouldn't require too many changes.

### Overview

Since we already fetch the public SSH key, but don't display it, it should be a matter of simply changing the SSH command's [`displayer`](https://github.com/digitalocean/doctl/blob/master/commands/displayers/key.go).

### How to fix it

We need to update the key `displayer` to show the public key field. The changes to the displayer would be as follows,

```diff
--- a/commands/displayers/key.go
+++ b/commands/displayers/key.go
@@ -31,13 +31,13 @@ func (ke *Key) JSON(out io.Writer) error {

 func (ke *Key) Cols() []string {
        return []string{
-               "ID", "Name", "FingerPrint",
+               "ID", "Name", "FingerPrint", "PublicKey",
        }
 }

 func (ke *Key) ColMap() map[string]string {
        return map[string]string{
-               "ID": "ID", "Name": "Name", "FingerPrint": "FingerPrint",
+               "ID": "ID", "Name": "Name", "FingerPrint": "FingerPrint", "PublicKey": "Public Key",
        }
 }

@@ -46,7 +46,7 @@ func (ke *Key) KV() []map[string]interface{} {

        for _, k := range ke.Keys {
                o := map[string]interface{}{
-                       "ID": k.ID, "Name": k.Name, "FingerPrint": k.Fingerprint,
+                       "ID": k.ID, "Name": k.Name, "FingerPrint": k.Fingerprint, "PublicKey": k.PublicKey,
                }

                out = append(out, o)
```

We'd also need to check that the tests still pass, and potentially update them. Our tests can be run from the root of the repo with `go test ./...`. We have both regular Go unit tests, and a suite of integration tests.

**Comment by kowshikRoy** [comment]
Please assign this to me. I will like to work on it.

**Comment by bentranter** [comment]
Sure @kowshikRoy, I'll assign it to you, although others still may work on it as this type of issue is pretty popular during Hacktoberfest. Thanks!
