### ISSUE TITLE
Proposal for creating Visual Studio Code extension.

### ISSUE THREAD

**Issue by nurmohammed840** [digitalocean/doctl#973]
### This is a Proposal for creating Visual Studio Code extension.

I am surprised by how user-friendly Digital Ocean  is! It has a beautiful user interface to interact with this service, Mainly via its website only.

But we  programmers wish that, It would be nice to have an extension for Visual Studio Code IDE. 
Just acknowledging ,Visual Studio Code is the most famous IDE among developers, Also it has many features that users would benefit from.

Some feature should include:
-  Monitoring 
- Management
- Account, Profile, Setting 
- SSL, Remote access
-  Tools

We would like to have an extension from  Digital Ocean for Visual Studio Code.
Something like Microsoft Azure.

**Comment by andrewsomething** [comment]
Hi @nurmohammed840,

Thanks for sharing this feedback. A DigitalOcean VS Code extension could be a great idea! Since issues in this repository are for tracking issues with our CLI `doctl`, I'm going to close this one for now.

I'd encourage you to share the idea over on https://ideas.digitalocean.com/

Thanks!
