### ISSUE TITLE
doctl apps create support for update existing apps

### ISSUE THREAD

**Issue by lbazetto** [digitalocean/doctl#989]
**What is the problem this feature would solve? Please describe.**

I have a few CI/CD pipelines to deploy different applications using the `doctl apps`command.
But at the moment, I have a step just to verify if the app exists and then, choose between `doctl apps create` for new apps or `doctl apps update` for existing ones.

**Describe the solution you'd like**
A new flag in the `doctl apps create --allow-update` or a new command, such as: `doctl apps create-update`

thanks :)

**Comment by Shanduur** [comment]
Hi. I would suggest to create flag (`-u | --update`) that will automatically existing app. If no one is working on it, I will take that.

**Comment by danaelhe** [comment]
Hi there,

Thanks for the write up. I was wondering if you'd be able to accomplish what you'd want with this linux work around:

`doctl apps update b2bb3-b332-b222 --spec-file data.yaml || doctl apps create --spec-file data.yaml`

that way it'd remove the step to verify if the app exists before. This workaround could remove the need to update doctl- unless there's a use case where the linux work around would not suffice?

**Comment by Shanduur** [comment]
@danaelhe I think, @lbazetto was referring to some CI/CD pipelines. Performing multiple commands in single action is often considered as bad practice, especially if those command chains are performing alternative actions.

However I think that approach of branched pipeline (`GET id; if not then CREATE; else UPDATE;`) might be a better idea in some scenarios.

Nevertheless, we write CLI tools to simplify communication with API. He could also use `curl` instead of `doctl`, as those are performing the same purpose here - sending request to API. I think that simplification might be beneficial in the long run to more people.

**Comment by danaelhe** [comment]
I see. I've left a comment on the PR continuing this conversation at #1038
